#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.lcj.entity
  mapperLocations: classpath:mapping/*.xml


---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://47.99.185.244:3306/boot
    username: root
    password: phantom3*
    driver-class-name: com.mysql.jdbc.Driver